version: '3'
services:
  backend:
    build: "."
    ports:
      - "80:80"
    volumes:
      - ".:/app"
    environment:
      ENV: "development"
    networks:
      - webnet
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
    networks:
      - webnet
    command: redis-server
  frontend:
    build: "./frontend"
    ports:
      - "8080:8080"
    volumes:
      - "./frontend:/app"
    environment:
      NODE_ENV: "dev"
networks:
  webnet:
