version: '3'
services:
  backend:
    build: "."
    ports:
      - "80:80"
    volumes:
      - ".:/app"
    environment:
      ENV: "development"
    networks:
      - webnet
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
    networks:
      - webnet
    command: redis-server
networks:
  webnet:
